/**
 * Farm Return Next Checkpoint 2, Vertical A — the client-side durable
 * offline outbox `ARCHITECTURE.md`'s "Offline / GPS job mode" section
 * requires (product-owner decision, 2026-09-01): "IndexedDB is the
 * canonical client-side durable outbox/store for offline-recorded events
 * ... a real transactional queue a browser tab reload/crash doesn't
 * lose, not a cache." A service-worker cache is deliberately NOT used as
 * the primary queue here (iOS Safari's historically incomplete
 * Background Sync support) — this module is fully correct on its own; a
 * service worker may additionally attempt best-effort automatic
 * `flush()` calls later, but nothing here depends on one existing.
 *
 * This module is deliberately generic across outbox item types
 * (`OutboxItemType`), not GPS-specific — Vertical C's own offline
 * Confirm actions (`ARCHITECTURE.md`'s "Confirm and telemetry capture
 * must queue locally") reuse the exact same queue, not a second one,
 * once that vertical exists to add its own item type and sync function.
 * Today's one real item type is `"telemetry_event"`
 * (`src/lib/farm-data/telemetry.ts`'s `TelemetryEventInput` shape).
 *
 * **Isomorphic-safe module, not `"use client"` or `server-only`**: this
 * file has no React import and nothing in it throws merely from being
 * imported during SSR — `indexedDB` is only ever read *inside* an
 * exported function body, never at module scope, so a Server Component
 * (or a test) that imports this module transitively never crashes; only
 * an actual *call* to one of these functions outside a browser rejects,
 * with a clear, specific error (`assertIndexedDbAvailable` below) rather
 * than an opaque `indexedDB is not defined` `ReferenceError`.
 *
 * **Deterministic idempotency keys, not generated here** — `id` is
 * always supplied by the caller (`crypto.randomUUID()` at real capture
 * time, `ARCHITECTURE.md`'s explicit requirement), never generated by
 * this module. `enqueue` is a safe no-op if an item with that `id`
 * already exists in the store *at any syncState* — re-enqueuing an
 * already-synced item (e.g. a component effect re-running) must never
 * regress it back to `"pending"` and cause a real server-side duplicate
 * insert on the next flush.
 *
 * **Every read/mutation is farm-scoped, by required `farmId` parameter —
 * Codex audit CRITICAL, `docs/farm-return-next/audit-logs/
 * 20260901T140609Z.md`.** IndexedDB is origin-wide, not per-user: on a
 * shared device, User B signing in after User A on the same browser
 * would otherwise have this module's `getAll()`/`getPending()`/`flush()`
 * indiscriminately read and process whatever User A's session had left
 * queued, regardless of which farm it belonged to — a real cross-tenant
 * data-exposure bug, this module's own equivalent of the `farm_id`
 * scoping every RLS policy elsewhere in this app already enforces
 * server-side. This module cannot itself verify a caller is genuinely
 * authorised for a given `farmId` (it has no concept of the current
 * session — that is the calling app's job, the same as every other
 * client-side farm-scoped read in this app trusts its own session
 * context before ever reaching a query), but it now guarantees it never
 * operates over the whole origin-wide store regardless of which farm is
 * asked for. `clearFarm`/`clearAll` (below) let a real caller purge
 * on logout — not wired to anything automatically yet, since no real
 * consumer of this module exists (see `ARCHITECTURE.md`'s "Deliberately
 * NOT shipped this increment" note); whichever future caller adds real
 * GPS capture must call `clearFarm`/`clearAll` from the app's own
 * sign-out path.
 *
 * **`DB_VERSION` bump discipline — Codex audit HIGH, round 2 (same log
 * above).** Round 1 added the `farmId` index but left `DB_VERSION`
 * unchanged; IndexedDB's `onupgradeneeded` only fires when the requested
 * version is *higher* than what a browser already has stored, so a
 * browser that had already opened this database under the schema before
 * that fix would never gain the new index and `store.index("farmId")`
 * would throw `NotFoundError` for every real user who had used the app
 * even once before this shipped. Fixed: `DB_VERSION` is now 2, and
 * `onupgradeneeded` creates the store's indexes idempotently (checking
 * `indexNames.contains(...)` rather than only checking whether the
 * *store itself* exists) so an in-place upgrade from a genuine v1
 * database gains the new index without any data loss — see
 * `describe("schema upgrade", ...)` in this module's own test file,
 * which exercises exactly that upgrade path against a real (not
 * hand-rolled) v1-shaped database. **Any future schema change to this
 * store must bump `DB_VERSION` again** — this is not optional, and this
 * file having gotten it wrong once already is exactly why this paragraph
 * exists.
 *
 * **At-least-once delivery, not exactly-once — every `syncFn` MUST be
 * idempotent (safe to call more than once for the same item) — Codex
 * audit HIGH, round 2, same log.** Round 1's atomic `tryClaimItem`
 * genuinely prevents two callers from *simultaneously* claiming the same
 * item (the browser serialises the underlying transaction), but round
 * 1's own doc comment overclaimed what that guarantees: a `"syncing"`
 * item reclaimed as stale (see `reclaimStale` below) *while its original
 * `syncFn` call is still genuinely running* — a real risk for any
 * `syncFn` slower than expected, not just a crashed tab — can still
 * result in two real `syncFn` invocations for the same item, since
 * nothing can forcibly cancel an in-flight `fetch`/Supabase call once
 * started. This module now closes the *local bookkeeping* half of that
 * risk (via `claimToken` below — a stale reclaim's own eventual
 * completion write can never clobber a newer claim's state), but the
 * *remote* half — whatever `syncFn` actually does server-side — must be
 * safe to run twice for the same item. `src/lib/farm-data/telemetry.ts`'s
 * `insertTelemetryEvent` already satisfies this by construction (its own
 * `23505`-retry-safety pattern); any future item type's `syncFn` must do
 * the same, the same way SQS/most real at-least-once queues push
 * idempotency to the consumer rather than promising exactly-once
 * delivery no local queue alone can actually guarantee.
 *
 * **`claimToken`-guarded completion writes**: `tryClaimItem` stamps each
 * claim with a fresh, random `claimToken`. The completion writes after
 * `syncFn` resolves/rejects (`completeClaim` below) are conditional on
 * that exact token still being the item's current one — if a later
 * claim (a stale reclaim, or another tab) has since overwritten it, this
 * call's own completion is a stale no-op rather than an unconditional
 * overwrite that would silently clobber the newer claim's own state.
 *
 * **`reclaimStale` is a separate, explicit, opt-in function — not run
 * automatically inside `flush()`.** Round 1 had `flush()` itself
 * silently reclaim any `"syncing"` item stale past a fixed 2-minute
 * threshold on every call — too short a window to safely assume no
 * legitimate `syncFn` is still running (a real risk the round-2 finding
 * above is about), and baked into the hot path every single `flush()`
 * call takes. Moved out to its own function with a much more
 * conservative default threshold (30 minutes) that a caller invokes
 * deliberately (e.g. once at app startup) — a genuinely abandoned item
 * (a tab that closed or crashed mid-sync) still gets un-stuck
 * eventually, but `flush()` itself never silently reaches into another
 * in-flight claim's territory as a side effect of normal operation.
 */

const DB_NAME = "farm-return-outbox";
const DB_VERSION = 2;
const STORE_NAME = "items";
const SYNC_STATE_INDEX = "syncState";
const FARM_ID_INDEX = "farmId";

export type OutboxItemType = "telemetry_event";

export type OutboxSyncState = "pending" | "syncing" | "synced" | "failed";

export interface OutboxItem<T = unknown> {
  /** Client-generated idempotency key — never generated by this module.
   * See this file's own header comment. */
  id: string;
  type: OutboxItemType;
  farmId: string;
  payload: T;
  /** ISO datetime this item was first enqueued (not when it was
   * captured — a caller's own payload carries its own capture
   * timestamp, e.g. `TelemetryEventInput.recordedAt`). */
  enqueuedAt: string;
  syncState: OutboxSyncState;
  attempts: number;
  lastError?: string;
  lastAttemptAt?: string;
  /** Set only while `syncState === "syncing"` — a fresh random token
   * stamped by whichever `tryClaimItem` call most recently claimed this
   * item. See this file's own header comment ("claimToken-guarded
   * completion writes") for why. */
  claimToken?: string;
}

function assertIndexedDbAvailable(): void {
  if (typeof indexedDB === "undefined") {
    throw new Error(
      "[offline/outbox] indexedDB is not available in this environment — this module must only be called from a browser client, never during SSR or in a server-only context.",
    );
  }
}

let dbPromise: Promise<IDBDatabase> | null = null;

/**
 * Opens (and memoizes) the one shared connection this module uses.
 * Memoized as a promise, not a resolved value, so concurrent early
 * callers all await the same in-flight open rather than racing to open
 * the database twice.
 *
 * Index creation is idempotent by construction (`indexNames.contains`
 * checked individually, not just whether the store itself exists) —
 * `onupgradeneeded` fires for a genuine v1->v2 upgrade with the store
 * already present and only `SYNC_STATE_INDEX` existing, and must create
 * `FARM_ID_INDEX` in that case too, not skip the whole block because the
 * store already existed (the exact bug `DB_VERSION`'s own bump fixes —
 * see this file's header comment).
 */
function openDb(): Promise<IDBDatabase> {
  assertIndexedDbAvailable();
  if (dbPromise) return dbPromise;
  dbPromise = new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = () => {
      const db = request.result;
      const store = db.objectStoreNames.contains(STORE_NAME)
        ? request.transaction!.objectStore(STORE_NAME)
        : db.createObjectStore(STORE_NAME, { keyPath: "id" });
      if (!store.indexNames.contains(SYNC_STATE_INDEX)) {
        store.createIndex(SYNC_STATE_INDEX, "syncState", { unique: false });
      }
      if (!store.indexNames.contains(FARM_ID_INDEX)) {
        store.createIndex(FARM_ID_INDEX, "farmId", { unique: false });
      }
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => {
      dbPromise = null; // a failed open must not permanently poison future calls
      reject(request.error ?? new Error("[offline/outbox] indexedDB.open failed"));
    };
  });
  return dbPromise;
}

function requestToPromise<T>(request: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error ?? new Error("[offline/outbox] IndexedDB request failed"));
  });
}

/**
 * Enqueues a new item for offline-durable sync. A safe no-op if an item
 * with this exact `id` is already present at any syncState — see this
 * file's own header comment for why re-enqueuing an already-synced item
 * must never regress its state.
 */
export async function enqueue<T>(item: Omit<OutboxItem<T>, "syncState" | "attempts">): Promise<void> {
  const db = await openDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    const store = tx.objectStore(STORE_NAME);
    const getRequest = store.get(item.id);
    getRequest.onsuccess = () => {
      if (getRequest.result) {
        // Already present at some syncState — no-op, do not overwrite.
        return;
      }
      store.put({ ...item, syncState: "pending", attempts: 0 } satisfies OutboxItem<T>);
    };
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("[offline/outbox] enqueue transaction failed"));
  });
}

async function getAllForFarm(farmId: string): Promise<OutboxItem[]> {
  const db = await openDb();
  const tx = db.transaction(STORE_NAME, "readonly");
  const store = tx.objectStore(STORE_NAME);
  const index = store.index(FARM_ID_INDEX);
  const all = await requestToPromise(index.getAll(farmId));
  return all as OutboxItem[];
}

/**
 * Every item belonging to `farmId` currently eligible to sync —
 * `"pending"` (never attempted) and `"failed"` (a prior attempt failed;
 * failure is retryable, not terminal — `ARCHITECTURE.md`'s "retry after
 * network failure" requirement). `"syncing"` items are deliberately
 * excluded, including a stale one — call `reclaimStale` first if you
 * want a genuinely abandoned item to become claimable again. Ordered by
 * `enqueuedAt` ascending — oldest first, the natural retry order for a
 * queue.
 *
 * **`farmId` is required, not optional** — Codex audit CRITICAL, see
 * this file's own header comment. A caller must always pass the current
 * session's own farm; there is no "give me everything regardless of
 * farm" variant of this function.
 */
export async function getPending(farmId: string): Promise<OutboxItem[]> {
  const items = await getAllForFarm(farmId);
  return items
    .filter((item) => item.syncState === "pending" || item.syncState === "failed")
    .sort((a, b) => a.enqueuedAt.localeCompare(b.enqueuedAt));
}

/** Every item belonging to `farmId` currently in the store, any
 * syncState — for diagnostics/UI (e.g. a future "N items waiting to
 * sync" indicator). `farmId` is required for the same reason
 * `getPending` requires it — see this file's own header comment. */
export async function getAll(farmId: string): Promise<OutboxItem[]> {
  return getAllForFarm(farmId);
}

/**
 * Atomically claims one item for processing — a single IndexedDB
 * transaction that reads the item's current state and, only if it is
 * genuinely claimable (`"pending"` or `"failed"`), writes it to
 * `"syncing"` with a fresh `claimToken`/`lastAttemptAt` and incremented
 * `attempts` in that same transaction. The browser serialises
 * transactions against the same object store — including across tabs of
 * the same origin — so two concurrent callers racing to claim the same
 * item can only ever have one succeed; the other's read (in its own,
 * later-ordered transaction) sees the item already `"syncing"` and
 * returns `null` without writing anything. Returns the claimed item (its
 * new, post-claim state, including the fresh `claimToken`) on success,
 * `null` if the item was not claimable (already claimed elsewhere,
 * already terminal, or concurrently removed). Deliberately does **not**
 * consider a stale `"syncing"` item claimable itself — see
 * `reclaimStale` below for that, and this file's own header comment for
 * why the two are now separate.
 */
async function tryClaimItem(id: string): Promise<OutboxItem | null> {
  const db = await openDb();
  return new Promise<OutboxItem | null>((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    const store = tx.objectStore(STORE_NAME);
    const getRequest = store.get(id);
    let claimed: OutboxItem | null = null;
    getRequest.onsuccess = () => {
      const existing = getRequest.result as OutboxItem | undefined;
      if (!existing) return; // removed concurrently (e.g. pruned) — nothing to claim
      if (existing.syncState !== "pending" && existing.syncState !== "failed") return; // lost the race, or already terminal — not an error
      claimed = {
        ...existing,
        syncState: "syncing",
        attempts: existing.attempts + 1,
        lastAttemptAt: new Date().toISOString(),
        claimToken: crypto.randomUUID(),
      };
      store.put(claimed);
    };
    tx.oncomplete = () => resolve(claimed);
    tx.onerror = () => reject(tx.error ?? new Error("[offline/outbox] claim transaction failed"));
  });
}

/**
 * Records the outcome of a claimed item's `syncFn` call — conditional on
 * `claimToken` still matching the item's current stored token. If it no
 * longer matches (a later claim, e.g. via `reclaimStale`, has since
 * overwritten it), this write is a stale no-op: the newer claim owns
 * this item's state now, and an old, slow completion must never clobber
 * it. See this file's own header comment ("claimToken-guarded completion
 * writes").
 */
async function completeClaim(id: string, claimToken: string, patch: Partial<OutboxItem>): Promise<void> {
  const db = await openDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    const store = tx.objectStore(STORE_NAME);
    const getRequest = store.get(id);
    getRequest.onsuccess = () => {
      const existing = getRequest.result as OutboxItem | undefined;
      if (!existing) return; // removed concurrently — nothing to complete
      if (existing.claimToken !== claimToken) return; // superseded by a newer claim — stale completion, no-op
      store.put({ ...existing, ...patch, claimToken: undefined });
    };
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("[offline/outbox] complete-claim transaction failed"));
  });
}

/** Removes an item outright — used only by `pruneSynced`/`clearFarm`/
 * `clearAll` below. There is deliberately no general-purpose "delete a
 * pending item" export: a queued-but-not-yet-synced item represents a
 * real farmer action that must not silently disappear (the same "never
 * assume application code is the only writer" discipline applied to
 * this module's own callers — nothing in this app should be able to
 * quietly drop an unsynced telemetry point or Confirm action, other than
 * an explicit, whole-farm sign-out purge). */
async function removeItem(id: string): Promise<void> {
  const db = await openDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    tx.objectStore(STORE_NAME).delete(id);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("[offline/outbox] delete transaction failed"));
  });
}

export interface FlushResult {
  synced: string[];
  failed: { id: string; error: string }[];
}

/**
 * Attempts to sync every claimable (`"pending"`/`"failed"`) item
 * belonging to `farmId`, one at a time (sequential, not parallel — keeps
 * a stable, inspectable per-item order and avoids overwhelming a
 * just-reconnected, possibly-poor connection with a burst of concurrent
 * requests). `syncFn` is supplied by the caller (never hardcoded here)
 * so this module stays agnostic of any specific item type's real sync
 * call — e.g. wiring `"telemetry_event"` items to
 * `@/lib/farm-data/telemetry`'s `insertTelemetryEvent` is the caller's
 * job, not this module's (this file must never import a `server-only`
 * module — it runs in the browser). **`syncFn` must be idempotent** —
 * see this file's own header comment ("At-least-once delivery, not
 * exactly-once").
 *
 * One item's failure is caught and recorded, never thrown out of
 * `flush()` itself and never blocking the remaining items — the
 * `ARCHITECTURE.md` "partial-failure recovery" requirement. `flush()`
 * itself never reclaims a stale `"syncing"` item — call `reclaimStale`
 * separately first if you want that (see this file's own header comment
 * for why the two are no longer combined).
 */
export async function flush<T = unknown>(
  farmId: string,
  syncFn: (item: OutboxItem<T>) => Promise<void>,
): Promise<FlushResult> {
  const candidates = await getPending(farmId);
  const result: FlushResult = { synced: [], failed: [] };
  for (const candidate of candidates) {
    const claimed = await tryClaimItem(candidate.id);
    if (!claimed) continue; // lost the race to a concurrent flush, or no longer claimable
    const claimToken = claimed.claimToken!;
    try {
      await syncFn(claimed as OutboxItem<T>);
      await completeClaim(claimed.id, claimToken, { syncState: "synced" });
      result.synced.push(claimed.id);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`[offline/outbox] item ${claimed.id} (${claimed.type}) failed to sync:`, error);
      await completeClaim(claimed.id, claimToken, { syncState: "failed", lastError: message });
      result.failed.push({ id: claimed.id, error: message });
    }
  }
  return result;
}

/** Conservative default for `reclaimStale` — long enough that no
 * legitimate `syncFn` call for any item type this module currently
 * knows about should still be running, short enough that a genuinely
 * abandoned item (a closed/crashed tab) does not stay stuck for an
 * unreasonable time. */
const DEFAULT_RECLAIM_STALE_MS = 30 * 60 * 1000;

/**
 * Reclaims every item belonging to `farmId` that has sat in `"syncing"`
 * for longer than `olderThanMs` (default 30 minutes) back to
 * `"pending"`, so a genuinely abandoned item (the tab that claimed it
 * closed or crashed mid-request, so neither `flush()`'s success nor
 * failure handler ever ran) is retried on a future `flush()` call rather
 * than stuck forever. **Deliberately not called automatically by
 * `flush()`** — a real caller should invoke this explicitly, e.g. once
 * at app startup, not as a hidden side effect of every sync attempt —
 * see this file's own header comment for the full reasoning (round 2's
 * "at-least-once delivery" finding). Returns the number of items
 * reclaimed.
 */
export async function reclaimStale(farmId: string, olderThanMs: number = DEFAULT_RECLAIM_STALE_MS): Promise<number> {
  const all = await getAllForFarm(farmId);
  let reclaimed = 0;
  for (const item of all) {
    if (
      item.syncState === "syncing" &&
      item.lastAttemptAt !== undefined &&
      Date.now() - new Date(item.lastAttemptAt).getTime() > olderThanMs
    ) {
      // item.claimToken is always set alongside syncState "syncing" --
      // the only code path that sets "syncing" is tryClaimItem, which
      // always also stamps a fresh claimToken in the same write.
      await completeClaim(item.id, item.claimToken!, { syncState: "pending" });
      reclaimed += 1;
    }
  }
  return reclaimed;
}

/**
 * Deletes every `"synced"` item belonging to `farmId` older than
 * `maxAgeMs` (default 24h) — explicit opt-in cleanup, never automatic/
 * implicit inside `flush()` itself. A synced item is already durably
 * persisted server-side (that is what `"synced"` means), so keeping it
 * in the local outbox indefinitely only wastes local storage; pruning it
 * is safe precisely because it is no longer the only copy of that fact
 * anywhere.
 */
export async function pruneSynced(farmId: string, maxAgeMs: number = 24 * 60 * 60 * 1000): Promise<number> {
  const all = await getAllForFarm(farmId);
  const cutoff = Date.now() - maxAgeMs;
  let pruned = 0;
  for (const item of all) {
    if (item.syncState === "synced" && new Date(item.enqueuedAt).getTime() < cutoff) {
      await removeItem(item.id);
      pruned += 1;
    }
  }
  return pruned;
}

/**
 * Removes every item belonging to `farmId`, regardless of syncState —
 * for a real sign-out path to call (once one exists — see this file's
 * own header comment; not wired to anything automatically this
 * increment). Unlike `pruneSynced`, this genuinely discards unsynced
 * items too: on sign-out, this session must not leave another user's
 * farm data (even queued-but-not-yet-synced) sitting in this browser's
 * shared origin storage.
 */
export async function clearFarm(farmId: string): Promise<void> {
  const all = await getAllForFarm(farmId);
  for (const item of all) {
    await removeItem(item.id);
  }
}

/** Removes every item for every farm — the whole-origin equivalent of
 * `clearFarm`, for a sign-out path that does not know (or does not want
 * to trust) which specific farms this browser may have queued data for. */
export async function clearAll(): Promise<void> {
  const db = await openDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    tx.objectStore(STORE_NAME).clear();
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("[offline/outbox] clear transaction failed"));
  });
}

/** Test-only: forces the next call to re-open the database rather than
 * reuse the memoized connection — needed because each test wants its own
 * isolated `fake-indexeddb` database, and this module's real production
 * behaviour (one shared connection for the page's lifetime) is
 * deliberately not reset in a real browser. */
export function __resetForTests(): void {
  dbPromise = null;
}
