/**
 * Farm Return Next Checkpoint 2, Vertical A — the client-side durable
 * offline outbox `ARCHITECTURE.md`'s "Offline / GPS job mode" section
 * requires (product-owner decision, 2026-09-01): "IndexedDB is the
 * canonical client-side durable outbox/store for offline-recorded events
 * ... a real transactional queue a browser tab reload/crash doesn't
 * lose, not a cache." A service-worker cache is deliberately NOT used as
 * the primary queue here (iOS Safari's historically incomplete
 * Background Sync support) — this module is fully correct on its own; a
 * service worker may additionally attempt best-effort automatic
 * `flush()` calls later, but nothing here depends on one existing.
 *
 * This module is deliberately generic across outbox item types
 * (`OutboxItemType`), not GPS-specific — Vertical C's own offline
 * Confirm actions (`ARCHITECTURE.md`'s "Confirm and telemetry capture
 * must queue locally") reuse the exact same queue, not a second one,
 * once that vertical exists to add its own item type and sync function.
 * Today's one real item type is `"telemetry_event"`
 * (`src/lib/farm-data/telemetry.ts`'s `TelemetryEventInput` shape).
 *
 * **Isomorphic-safe module, not `"use client"` or `server-only`**: this
 * file has no React import and nothing in it throws merely from being
 * imported during SSR — `indexedDB` is only ever read *inside* an
 * exported function body, never at module scope, so a Server Component
 * (or a test) that imports this module transitively never crashes; only
 * an actual *call* to one of these functions outside a browser rejects,
 * with a clear, specific error (`assertIndexedDbAvailable` below) rather
 * than an opaque `indexedDB is not defined` `ReferenceError`.
 *
 * **Deterministic idempotency keys, not generated here** — `id` is
 * always supplied by the caller (`crypto.randomUUID()` at real capture
 * time, `ARCHITECTURE.md`'s explicit requirement), never generated by
 * this module. `enqueue` is a safe no-op if an item with that `id`
 * already exists in the store *at any syncState* — re-enqueuing an
 * already-synced item (e.g. a component effect re-running) must never
 * regress it back to `"pending"` and cause a real server-side duplicate
 * insert on the next flush.
 *
 * **Partial-failure recovery**: `flush()` processes queued items one at
 * a time, catching each item's own failure independently — one item
 * failing to sync (a real server rejection, a transient network error)
 * never blocks or corrupts the rest of the batch, and never throws out
 * of `flush()` itself. A *systemic* failure (IndexedDB itself unusable —
 * private browsing storage restrictions, the store not existing) does
 * reject `flush()`'s own promise, since there is no per-item recovery
 * possible from that.
 */

const DB_NAME = "farm-return-outbox";
const DB_VERSION = 1;
const STORE_NAME = "items";
const SYNC_STATE_INDEX = "syncState";

export type OutboxItemType = "telemetry_event";

export type OutboxSyncState = "pending" | "syncing" | "synced" | "failed";

export interface OutboxItem<T = unknown> {
  /** Client-generated idempotency key — never generated by this module.
   * See this file's own header comment. */
  id: string;
  type: OutboxItemType;
  farmId: string;
  payload: T;
  /** ISO datetime this item was first enqueued (not when it was
   * captured — a caller's own payload carries its own capture
   * timestamp, e.g. `TelemetryEventInput.recordedAt`). */
  enqueuedAt: string;
  syncState: OutboxSyncState;
  attempts: number;
  lastError?: string;
  lastAttemptAt?: string;
}

function assertIndexedDbAvailable(): void {
  if (typeof indexedDB === "undefined") {
    throw new Error(
      "[offline/outbox] indexedDB is not available in this environment — this module must only be called from a browser client, never during SSR or in a server-only context.",
    );
  }
}

let dbPromise: Promise<IDBDatabase> | null = null;

/**
 * Opens (and memoizes) the one shared connection this module uses.
 * Memoized as a promise, not a resolved value, so concurrent early
 * callers all await the same in-flight open rather than racing to open
 * the database twice.
 */
function openDb(): Promise<IDBDatabase> {
  assertIndexedDbAvailable();
  if (dbPromise) return dbPromise;
  dbPromise = new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        const store = db.createObjectStore(STORE_NAME, { keyPath: "id" });
        store.createIndex(SYNC_STATE_INDEX, "syncState", { unique: false });
      }
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => {
      dbPromise = null; // a failed open must not permanently poison future calls
      reject(request.error ?? new Error("[offline/outbox] indexedDB.open failed"));
    };
  });
  return dbPromise;
}

function requestToPromise<T>(request: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error ?? new Error("[offline/outbox] IndexedDB request failed"));
  });
}

/**
 * Enqueues a new item for offline-durable sync. A safe no-op if an item
 * with this exact `id` is already present at any syncState — see this
 * file's own header comment for why re-enqueuing an already-synced item
 * must never regress its state.
 */
export async function enqueue<T>(item: Omit<OutboxItem<T>, "syncState" | "attempts">): Promise<void> {
  const db = await openDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    const store = tx.objectStore(STORE_NAME);
    const getRequest = store.get(item.id);
    getRequest.onsuccess = () => {
      if (getRequest.result) {
        // Already present at some syncState — no-op, do not overwrite.
        return;
      }
      store.put({ ...item, syncState: "pending", attempts: 0 } satisfies OutboxItem<T>);
    };
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("[offline/outbox] enqueue transaction failed"));
  });
}

/**
 * Every item currently eligible to sync — `"pending"` (never attempted)
 * and `"failed"` (a prior attempt failed; failure is retryable, not
 * terminal — `ARCHITECTURE.md`'s "retry after network failure"
 * requirement). `"syncing"` items are deliberately excluded: a genuine
 * concurrent `flush()` call (two tabs, or a manual + a background-sync
 * trigger overlapping) must not pick up the same item twice — see
 * `flush()`'s own doc comment for what happens to a `"syncing"` item
 * whose flush never completed (e.g. the tab was closed mid-sync).
 * Ordered by `enqueuedAt` ascending — oldest first, the natural retry
 * order for a queue.
 */
export async function getPending(): Promise<OutboxItem[]> {
  const db = await openDb();
  const tx = db.transaction(STORE_NAME, "readonly");
  const store = tx.objectStore(STORE_NAME);
  const all = await requestToPromise(store.getAll());
  return (all as OutboxItem[])
    .filter((item) => item.syncState === "pending" || item.syncState === "failed")
    .sort((a, b) => a.enqueuedAt.localeCompare(b.enqueuedAt));
}

/** Every item currently in the store, any syncState — for diagnostics/UI
 * (e.g. a future "N items waiting to sync" indicator), not used by
 * `flush()` itself. */
export async function getAll(): Promise<OutboxItem[]> {
  const db = await openDb();
  const tx = db.transaction(STORE_NAME, "readonly");
  const store = tx.objectStore(STORE_NAME);
  const all = await requestToPromise(store.getAll());
  return all as OutboxItem[];
}

async function updateItem(id: string, patch: Partial<OutboxItem>): Promise<void> {
  const db = await openDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    const store = tx.objectStore(STORE_NAME);
    const getRequest = store.get(id);
    getRequest.onsuccess = () => {
      const existing = getRequest.result as OutboxItem | undefined;
      if (!existing) return; // item was removed (e.g. pruned) concurrently — nothing to update
      store.put({ ...existing, ...patch });
    };
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("[offline/outbox] update transaction failed"));
  });
}

/** Removes an item outright — used only by `pruneSynced` below. There is
 * deliberately no general-purpose "delete a pending item" export: a
 * queued-but-not-yet-synced item represents a real farmer action that
 * must not silently disappear (the same "never assume application code
 * is the only writer" discipline applied to this module's own callers —
 * nothing in this app should be able to quietly drop an unsynced
 * telemetry point or Confirm action). */
async function removeItem(id: string): Promise<void> {
  const db = await openDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    tx.objectStore(STORE_NAME).delete(id);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("[offline/outbox] delete transaction failed"));
  });
}

export interface FlushResult {
  synced: string[];
  failed: { id: string; error: string }[];
}

/**
 * Attempts to sync every pending/failed item, one at a time (sequential,
 * not parallel — keeps a stable, inspectable per-item order and avoids
 * overwhelming a just-reconnected, possibly-poor connection with a burst
 * of concurrent requests). `syncFn` is supplied by the caller (never
 * hardcoded here) so this module stays agnostic of any specific item
 * type's real sync call — e.g. wiring `"telemetry_event"` items to
 * `@/lib/farm-data/telemetry`'s `insertTelemetryEvent` is the caller's
 * job, not this module's (this file must never import a `server-only`
 * module — it runs in the browser).
 *
 * One item's failure is caught and recorded, never thrown out of
 * `flush()` itself and never blocking the remaining items — the
 * `ARCHITECTURE.md` "partial-failure recovery" requirement. `flush()`
 * itself first reclaims any item left in `"syncing"` (a tab closed or
 * crashed mid-request, so neither the success nor failure handler ever
 * ran) back to `"pending"` before reading `getPending()` — see
 * `reclaimAbandonedSyncing()` below — so a genuinely abandoned in-flight
 * item is retried on the next flush rather than stuck forever in a state
 * `getPending()` never returns.
 */
export async function flush<T = unknown>(syncFn: (item: OutboxItem<T>) => Promise<void>): Promise<FlushResult> {
  await reclaimAbandonedSyncing();
  const items = await getPending();
  const result: FlushResult = { synced: [], failed: [] };
  for (const item of items) {
    await updateItem(item.id, { syncState: "syncing", attempts: item.attempts + 1, lastAttemptAt: new Date().toISOString() });
    try {
      await syncFn(item as OutboxItem<T>);
      await updateItem(item.id, { syncState: "synced" });
      result.synced.push(item.id);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`[offline/outbox] item ${item.id} (${item.type}) failed to sync:`, error);
      await updateItem(item.id, { syncState: "failed", lastError: message });
      result.failed.push({ id: item.id, error: message });
    }
  }
  return result;
}

/**
 * Reclaims any item stuck in `"syncing"` back to `"pending"` — the only
 * way an item ends up in `"syncing"` outside of `flush()`'s own brief
 * per-item window is a tab closing (or crashing) mid-request, since
 * `flush()` is sequential and always resolves each item's state before
 * moving to the next. Called at the start of every `flush()` so an
 * abandoned in-flight item is retried on the next attempt rather than
 * silently excluded forever (`getPending()` never returns `"syncing"`
 * items, by design, to avoid two concurrent `flush()` calls double-
 * processing the same item — see `getPending()`'s own doc comment).
 */
async function reclaimAbandonedSyncing(): Promise<void> {
  const all = await getAll();
  for (const item of all) {
    if (item.syncState === "syncing") {
      await updateItem(item.id, { syncState: "pending" });
    }
  }
}

/**
 * Deletes every `"synced"` item older than `maxAgeMs` (default 24h) —
 * explicit opt-in cleanup, never automatic/implicit inside `flush()`
 * itself. A synced item is already durably persisted server-side (that
 * is what `"synced"` means), so keeping it in the local outbox indefinitely
 * only wastes local storage; pruning it is safe precisely because it is
 * no longer the only copy of that fact anywhere.
 */
export async function pruneSynced(maxAgeMs: number = 24 * 60 * 60 * 1000): Promise<number> {
  const all = await getAll();
  const cutoff = Date.now() - maxAgeMs;
  let pruned = 0;
  for (const item of all) {
    if (item.syncState === "synced" && new Date(item.enqueuedAt).getTime() < cutoff) {
      await removeItem(item.id);
      pruned += 1;
    }
  }
  return pruned;
}

/** Test-only: forces the next call to re-open the database rather than
 * reuse the memoized connection — needed because each test wants its own
 * isolated `fake-indexeddb` database, and this module's real production
 * behaviour (one shared connection for the page's lifetime) is
 * deliberately not reset in a real browser. */
export function __resetForTests(): void {
  dbPromise = null;
}
